### ISSUE TITLE
Inertia-link not working in pagination

### ISSUE THREAD

**Issue by knobik** [protonemedia/inertiajs-tables-laravel-query-builder#55] opened 2022-01-03 07:20 UTC
The fix is to import

`import {Link} from '@inertiajs/inertia-vue3';` in the Pagination.vue and use `link` instead of the `inertia-link`

**Comment by luismabenitez** [comment] 2022-01-20 17:49
+1

**Comment by javitrujillo99** [comment] 2022-01-25 18:59
+1

**Comment by acepoblete** [comment] 2022-01-25 23:22
+1

**Comment by inikoo** [comment] 2022-02-07 08:29
+1

**Comment by pascalbaljet** [comment] 2022-02-08 14:45
Duplicate of #36

**Closed by pascalbaljet** 2022-02-08 14:45 UTC
